### ISSUE TITLE
Uncaught Error: Minified React error #31;

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#241]
### What
https://hunger.openfoodfacts.org/questions
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1689815/193525584-9e459117-bd0f-4fd3-9fb2-53e8ab0a4834.png">

```
react-dom.production.min.js:189 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (react-dom.production.min.js:152:60)
    at e (react-dom.production.min.js:162:372)
    at wl (react-dom.production.min.js:192:323)
    at Cs (react-dom.production.min.js:294:9)
    at yu (react-dom.production.min.js:280:389)
    at vu (react-dom.production.min.js:280:320)
    at mu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at ou (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
pl @ react-dom.production.min.js:189
react-dom.production.min.js:283 Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (react-dom.production.min.js:152:60)
    at e (react-dom.production.min.js:162:372)
    at wl (react-dom.production.min.js:192:323)
    at Cs (react-dom.production.min.js:294:9)
    at yu (react-dom.production.min.js:280:389)
    at vu (react-dom.production.min.js:280:320)
    at mu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at ou (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
```

**Comment by alexfauquette** [comment]
surprisingly some times `categories` field returns either `undefined` or `{}` The problem was we did not handled the case of `{}`
