### ISSUE TITLE
White page in individual packaging screen

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#417]
### What

- [ ] White page in individual packaging screen
  - [ ] https://hunger.openfoodfacts.org/packaging?code=1234567890123

```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at useBuffer.ts:76:31
    at rs (react-dom.production.min.js:244:332)
    at ku (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:282:391
    at k (scheduler.production.min.js:13:203)
    at MessagePort.j (scheduler.production.min.js:14:128)
packaging:1          Failed to load resource: the server responded with a status of 404 ()
```

**Comment by alexfauquette** [comment]
My bad, could not test before merging due to CORS restrictions


The problem is that in `useBuffer`, we do `setData(data.products);`

But for a single product (for example when URL params have code=....) we have 

```json
{
  "product":{
  /** some data about the product **/
  },
   /** some data about the request status **/
}
```

Whereas without `code=...` we get 
```json
{
  "products": [
    {
    /** some data about one product **/
    },
    {
    /** some data about another product **/
    },
  ]
   /** some data about the request status **/
}
```
